//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageApplication_withef.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Image_table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
